sudo: required
dist: trusty
language: python

cache:
  pip: true
  directories:
  - "$HOME/.cargo"
  - "$HOME/kcov"

matrix:
  include:
  - python: "2.7"
    env: FEATURES=python2
  - python: "3.5"
    env: FEATURES=python3
  - python: "3.6"
    env: FEATURES=python3
  - python: "3.7-dev"
    env: FEATURES=python3
  allow_failures:
  - python: "3.7-dev"
    env: FEATURES=python3

env:
  global:
    - TRAVIS_RUST_VERSION=nightly
    - RUSTFLAGS="-C link-dead-code"
    - RUST_BACKTRACE=1
    - SCCACHE_DIR="$HOME/.cargo/sccache"
    - RUSTC_WRAPPER=sccache

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

before_install:
  - source ./ci/travis/setup.sh

install:
  - pip install setuptools-rust pytest pytest-benchmark

script:
  - source ./ci/travis/test.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: ./ci/travis/cover.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./ci/travis/guide.sh
    on:
      branch: master
      repo: PyO3/pyo3
      python: 3.6
    
