sudo: false
dist: xenial
language: python

cache:
  pip: true
  directories:
  - "$HOME/.cargo"

matrix:
  include:
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"

env:
  global:
    - TRAVIS_RUST_VERSION=nightly
    - RUSTFLAGS="-C link-dead-code"
    - RUST_BACKTRACE=1
    - SCCACHE_DIR="$HOME/.cargo/sccache"
    - RUSTC_WRAPPER=sccache
    - PATH="$HOME/.cargo/bin:$PATH"

before_install:
  - ./ci/travis/setup.sh

install:
  - pip install setuptools-rust

script:
  - ./ci/travis/test.sh

# deploy:
#   - provider: script
#     skip_cleanup: true
#     script: ./ci/travis/cover.sh
#     on:
#       branch: master
#   - provider: script
#     skip_cleanup: true
#     script: ./ci/travis/guide.sh
#     on:
#       branch: master
#       repo: PyO3/pyo3
#       python: 3.6
