[package]
name = 'hello'
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-cachan.fr>"]
build = "build.rs"

[dependencies]
pyo3 = "^0.2.6"
pyo3-built = { path = "../.." }

[build-dependencies]
built = "^0.3.0"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"
