name: Test

on:
  - push
  - pull_request

jobs:

  test_linux:
    name: Test (Linux)
    runs-on: ubuntu-latest
    env:
      OS: Linux
    strategy:
      matrix:
        include:
        - python-version: 3.7
          python-release: v3.7
          python-impl: CPython
        - python-version: 3.8
          python-release: v3.8
          python-impl: CPython
        - python-version: 3.9
          python-release: v3.9
          python-impl: CPython
        - python-version: "3.10"
          python-release: v3.10
          python-impl: CPython
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Rust stable
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - name: Install build dependencies
      run: python -m pip install setuptools-rust
    - name: Build example
      run: cd example && python setup.py build_ext --inplace
    - name: Check example
      run: cd example && python -c 'import pprint; import hello; pprint.pprint(hello.__build__)' 
